version: '3.1'

services:

    db:
        image: postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 4321:5432
        environment:
            POSTGRES_PASSWORD: example

    adminer:
        image: adminer
        ports:
            - 8000:8080

